In [8]:
## create an array that consist of 10 zeros,10 ones and 10 fives##
import numpy as np
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
y=np.ones(10)
print(y)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
z=np.full((10),5)
print(z)

[5 5 5 5 5 5 5 5 5 5]


In [16]:
v=(x,y,z)
print(v)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5]))


In [20]:
x=np.arange(30,71)
print(x)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
